services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    command: >
      /bin/sh -c "
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  mongo_data:
    driver: local
